my_resume={
    "name":"Aslin Delma.M",
    "e_mail":"maslindelma@gmail.com",
    "mobile_no":"6380151220",
    "soft_skills":["Willingness to learn","time management"],
    "hard_skills":["MS Office","typing"],
    "objective":"work for the organization",
    "educational_qualification":[{
        "level":"M.E",
        "institution":"Bethlahem Institute of Engineering",
        "place":"Karungal",
        "passed_out_year":2022,
        "percentage":85},
        {"level":"B.E",
        "institution":"Jeppiaar Srr Engineering College",
        "place":"Chennai",
        "passed_out_year":2019,
        "percentage":75},
        {"level":"HSC",
        "institution":"A.P.J.M Matric Hr.Sec School",
        "place":"Soosaipuram",
        "passed_out_year":2015,
        "percentage":87.5},
        {"level":"SSLC",
        "institution":"A.P.J.M Matric Hr.Sec School",
        "Place":"Soosaipuram",
        "passed_out_year":2013,
        "percentage":93.6}],
    "projects":[{"project_name":"Accessible Melanoma Detection Using Smart Phones And Mobile Image Analysis",
                 "year":2019,
                 "technology":"neural network"},
                {"project_name":"An Automated Tongue Image Segmentation For Diseases Diagnosis in Human Body",
                 "year":2022,
                 "technology":"k means clustering"}],
    "experience":[{"company_name":"Capestart",
                   "role":"project trainee",
                   "experience":1.5},
                   {"company_name":"Amazon",
                   "role":"Team leader",
                   "experience":2}],
    "hobbies":["Stitching clothes","Drawing","gardening","playing chess"],
    "personal_details":{
                "father's_name":"M.Mathias",
                "father's_occupation":"Mason",
                "languages_known":["Tamil","English"],
                "date_of_birth":"04-12-1997",
                "gender":"Female",
                "martial_status":"Single",
                "address":{
                     "door_no":"1-105C",
                     "street":"Vadakkuvilai",
                     "place":"Devicode",
                     "district":"Kanyakumari",
                     "pincode":"629178"
                     }},
    "declaration":"the above mentioned details are correct"}
print(my_resume["name"],my_resume["educational_qualification"][3]["percentage"])
print(my_resume["projects"][1]["year"],my_resume["projects"][1]["technology"])
print(my_resume["personal_details"]["address"]["pincode"])